export type ScrapedOffer = {
  id?: number;
  leverantorId?: number;
  leverantor: string;
  avtalNamn: string;
  prisOre?: number;
  totalAr: number;
  totalMan: number;
  besparing: number;
  typ: string;
  gron: boolean;
  braMiljoval?: boolean;
  sol?: boolean;
  vind?: boolean;
  vatten?: boolean;
  bio?: boolean;
  karnkraft?: boolean;
  energiKalla?: string;
  uppsTid?: string;
  uppsTidRaw?: number;
  uppsTidEnhet?: string;
  kampanj: string;
  nyttaKunder?: boolean;
  betalning?: string;
  fakturering?: string;
  kwh?: number;
  elArea?: string;
  leverantorUrl?: string;
  leverantorTelefon?: string;
  leverantorEpost?: string;
  källa: 'live' | 'scrape' | 'beräknad';
};
